### PR TITLE
Fixed umd rquire of the exports section in package.json

### PR DESCRIPTION
**Pull request by zeko77**

### CODE REVIEW

**Comment by zeko77** [comment]
I used the client in a plugin which compiles to umd. When I tried to consume the plugin, (webpack 5) bundler could not find the umd file, as extension on require was .umd.cjs.

**Comment by mythz** [comment]
thx for the PR, pretty sure you do but just want to confirm that you need a new release on npm right?

**Comment by zeko77** [comment]
Thanx for a lightning response.
Currently I am using modified version of the client, and I thought that I could contribute in a part that is not intrusive to your code base and agenda.

I am using modified client for two reasons:
1. I am working on a solution that uses BFF  identity server 7. It proxies the requests to the API.  When sending the SSE request to BFF, I need to include a  cross site forgery token in a header,  so I modified getEventSourceOptions() of the ServerEventsClient to support headers.

2. Webpack 5 static analysis complains with: require function is used in a way in which dependencies cannot be statically extracted
In my case I have narrowed it down Inspect class which I disabled temporarily.

So the conclusion:
1. The ability to add headers to ServerEventsClient (in combination with EventSource polifil)
2. No warnings in webpack 5 due to static analysis and use of require.
I have MacGywer-ed my way around my issues, but it would be cool to have it in original client.

**Comment by mythz** [comment]
Yeah happy to accept PRs for any non-intrusive changes to the client you might need.

The client no longer uses `require` which I've [changed to use dynamic imports](https://github.com/ServiceStack/servicestack-client/blob/master/src/index.ts#L3304-L3308) to workaround webpack static analysis issues, is it still complaining about the dynamic imports?

**Comment by zeko77** [comment]
Yes.
Lines:
/@servicestack/client/dist/servicestack-client.mjs 2843:14-38
/@servicestack/client/dist/servicestack-client.mjs 2844:14-38
Inspect class.
I can see the comment that it should resolve it, but I get the warnings.
webpack: 5.91.0

**Comment by mythz** [comment]
Sure unlikely we'd be able to get rid of warnings, but hopefully it shouldn't produce build errors.

**Pull request merged**
